### ISSUE TITLE
Add bashrc commands to ansible playbook

### ISSUE THREAD

**Issue by trevorbryant** [JohnHammond/ignition_key#4]
Need to configure the custom lines into `.bashrc`. Currently have the below.

```
- name: update-bashrc
  hosts: localhost
  connection: local
  become: true
  ignore_errors: true
  tasks:
    - name: run commands
      command: "{{ item }}"
      with_items:
        - "echo export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$' >> ~/.bashrc"
        - "echo export GOPATH=\$HOME/.go/ >> ~/.bashrc"
        - "echo export GOBIN=\$HOME/.go/bin >> ~/.bashrc"
        - "echo export PATH=\$PATH:\$GOBIN >> ~/.bashrc"
  tags:
    - update-bashrc
```

**Comment by laxmiamrutapadhi** [comment]
Consider using `blockinfile` instead of `command` for updating `.bashrc`.  
That way, Ansible won’t append duplicate lines on every run, and the playbook will stay idempotent and easier to maintain.  

```yaml
- name: update-bashrc
  hosts: localhost
  connection: local
  tasks:
    - name: Add custom bashrc lines
      blockinfile:
        path: ~/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'
          export GOPATH=$HOME/.go/
          export GOBIN=$HOME/.go/bin
          export PATH=$PATH:$GOBIN
```
